pylint allows 7.5

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -18,9 +18,16 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
+
+    # Run pylint, fail if score is below 7.5
     - name: Analysing the code with pylint, ignore j2l
       run: |
         pylint $(git ls-files '*.py') --ignore-path=src/api/j2l/* 
+        pylint_score=$?
+        if [ $pylint_score -lt 75 ]; then
+          echo "Pylint score is below 7.5"
+          exit 1
+        fi
     - name: Running unittests
       run: |
         python -m unittest
